### ISSUE TITLE
Archiving this repository

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/debugger#11]
I think that it would make sense for that repository to be archived

 - It has been inactive for nearly two years
 - It would prevent confusion with https://github.com/jupyterlab/debugger which now has an alpha release.
 - Most of the discussion on the in-progress implementation of the Jupyter debugger have been carried on other repositories (jupyter_client, xeus, jupyterlab/debugger).

cc @afshin @ellisonbg @rgbkrk @johanmabille @jtpio

**Comment by JohanMabille** [comment]
I agree.

**Comment by afshin** [comment]
I agree.

**Comment by damianavila** [comment]
+1

**Comment by SylvainCorlay** [comment]
This repository has been moved to jupyter-attic and is being archived.
